# Generated by Django 3.0.2 on 2022-07-04 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='IOHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_in', models.PositiveIntegerField()),
                ('quantity_out', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='inventory.Product', verbose_name='Product')),
            ],
        ),
    ]
